version: "3"
services:

  back:
    image: hgloves/front
    build: ./front/
    ports:
      - "80:80"
    networks:
      - api-tier
    restart: on-failure

  front:
    image: hgloves/back
    build: ./back/
    ports:
      - "3300:3300"
    networks:
      - api-tier
    restart: on-failure
    

networks:
  api-tier: